version: '2'

services:

  wordpress:
    image: wordpress:5-php7.0
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_PASSWORD: docker
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./logs:/var/log/apache2
    restart: always
  mysql:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: wordpress
    volumes:
      - ./db:/var/lib/mysql
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always