version: '2'

services:

  wordpress:
    image: wordpress:4.8.1-php7.0
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_PASSWORD: docker
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./logs:/var/log/apache2

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: wordpress
    volumes:
      - ./db:/db